export const PLANS = {
  free: {
    id: "free",
    name: "Free",
    price: 0,
    annualPrice: 0,
    maxLinks: 10,
    maxBioPages: 1,
    analyticsDays: 7,
    customSlug: false,
    csvExport: false,
    qrWatermark: true,
    apiAccess: false,
    utmBuilder: true,
    linkTags: false,
    linkExpiration: false,
    passwordProtection: false,
    qrCustomization: false,
    customDomain: false,
    bioPages: true,
    geoTargeting: false,
    deviceTargeting: false,
    bulkImport: false,
    webhooks: false,
    linkFolders: false,
    abTesting: false,
    linkScheduling: false,
    deepAnalytics: false,
    teamCollaboration: false,
    trialDays: 0,
    description: "个人体验，永久免费",
    badge: null as string | null,
  },
  starter: {
    id: "starter",
    name: "Starter",
    price: 5,
    annualPrice: 42,
    maxLinks: 50,
    maxBioPages: 3,
    analyticsDays: 30,
    customSlug: true,
    csvExport: false,
    qrWatermark: false,
    apiAccess: false,
    utmBuilder: true,
    linkTags: true,
    linkExpiration: false,
    passwordProtection: false,
    qrCustomization: true,
    customDomain: false,
    bioPages: true,
    geoTargeting: false,
    deviceTargeting: false,
    bulkImport: false,
    webhooks: false,
    linkFolders: true,
    abTesting: false,
    linkScheduling: false,
    deepAnalytics: false,
    teamCollaboration: false,
    trialDays: 7,
    description: "个人创作者与小团队",
    badge: "7天免费试用" as string | null,
  },
  pro: {
    id: "pro",
    name: "Pro",
    price: 12,
    annualPrice: 99,
    maxLinks: 1000,
    maxBioPages: 10,
    analyticsDays: 90,
    customSlug: true,
    csvExport: true,
    qrWatermark: false,
    apiAccess: true,
    utmBuilder: true,
    linkTags: true,
    linkExpiration: true,
    passwordProtection: true,
    qrCustomization: true,
    customDomain: true,
    bioPages: true,
    geoTargeting: true,
    deviceTargeting: true,
    bulkImport: true,
    webhooks: true,
    linkFolders: true,
    abTesting: true,
    linkScheduling: true,
    deepAnalytics: true,
    teamCollaboration: false,
    trialDays: 7,
    description: "专业用户与营销团队",
    badge: "最受欢迎" as string | null,
  },
  business: {
    id: "business",
    name: "Business",
    price: 39,
    annualPrice: 329,
    maxLinks: -1,
    maxBioPages: -1,
    analyticsDays: 365,
    customSlug: true,
    csvExport: true,
    qrWatermark: false,
    apiAccess: true,
    utmBuilder: true,
    linkTags: true,
    linkExpiration: true,
    passwordProtection: true,
    qrCustomization: true,
    customDomain: true,
    bioPages: true,
    geoTargeting: true,
    deviceTargeting: true,
    bulkImport: true,
    webhooks: true,
    linkFolders: true,
    abTesting: true,
    linkScheduling: true,
    deepAnalytics: true,
    teamCollaboration: true,
    trialDays: 14,
    description: "企业与高流量场景",
    badge: null as string | null,
  },
} as const;

export type PlanId = keyof typeof PLANS;

export function getPlanLimits(plan: string) {
  if (plan === "starter") return PLANS.starter;
  if (plan === "pro") return PLANS.pro;
  if (plan === "business") return PLANS.business;
  return PLANS.free;
}

export function isPro(plan: string) {
  return plan === "pro" || plan === "business" || plan === "starter";
}

export function isPaidPlan(plan: string) {
  return plan !== "free";
}

export function planFromPriceId(priceId: string): string {
  const map: Record<string, string> = {
    [process.env.STRIPE_STARTER_PRICE_ID ?? "__none__"]: "starter",
    [process.env.STRIPE_STARTER_ANNUAL_PRICE_ID ?? "__none__"]: "starter",
    [process.env.STRIPE_PRO_PRICE_ID ?? "__none__"]: "pro",
    [process.env.STRIPE_PRO_ANNUAL_PRICE_ID ?? "__none__"]: "pro",
    [process.env.STRIPE_BUSINESS_PRICE_ID ?? "__none__"]: "business",
    [process.env.STRIPE_BUSINESS_ANNUAL_PRICE_ID ?? "__none__"]: "business",
  };
  return map[priceId] ?? "pro";
}