-- AlterTable
ALTER TABLE "Link" ADD COLUMN "tags" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Link" ADD COLUMN "utmSource" TEXT;
ALTER TABLE "Link" ADD COLUMN "utmMedium" TEXT;
ALTER TABLE "Link" ADD COLUMN "utmCampaign" TEXT;
ALTER TABLE "Link" ADD COLUMN "utmTerm" TEXT;
ALTER TABLE "Link" ADD COLUMN "utmContent" TEXT;
ALTER TABLE "Link" ADD COLUMN "expiresAt" TIMESTAMP(3);
ALTER TABLE "Link" ADD COLUMN "passwordHash" TEXT;
ALTER TABLE "Link" ADD COLUMN "qrColor" TEXT DEFAULT '#000000';